### ISSUE TITLE
Error TTY mode is not supported on Windows platform

### ISSUE THREAD

**Issue by angelinchaustipy** [MtDalPizzol/laravel-viltify#3]
Good morning!

I'm trying to install following the steps above, but I'm getting the following error:

|  Symfony\Component\Process\Exception\RuntimeException |
| --- |
|  TTY mode is not supported on Windows platform |
| at vue3\vendor\symfony\process\Process.php:1061|

![image](https://user-images.githubusercontent.com/13540008/147358001-1d26bcba-1b3f-42dd-affc-7dc3427a7b9d.png)

Greetings!

**Comment by MtDalPizzol** [comment]
Windows is only supported via WSL as explained in the Requirements section of the README. Also, based in your project folder name, I'm guessing you trying to use Vue 3, but this only supports Vue 2 at the moment since stable support for Vuetify 3 is schedule only for February 2022.
