### ISSUE TITLE
composer require error

### ISSUE THREAD

**Issue by thomasdeater** [MtDalPizzol/laravel-viltify#5]
On a fresh installation of Laravel 9.1.0 (MacOS 12.2.1), I'm getting a composer error:

`cd viltify

🔋  15:36 in viltify/
› composer require dalpizzol/laravel-viltify

Using version ^0.1.2 for dalpizzol/laravel-viltify
./composer.json has been updated
Running composer update dalpizzol/laravel-viltify
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires dalpizzol/laravel-viltify ^0.1.2 -> satisfiable by dalpizzol/laravel-viltify[v0.1.2].
    - dalpizzol/laravel-viltify v0.1.2 requires illuminate/filesystem ^8.42 -> found illuminate/filesystem[v8.42.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require dalpizzol/laravel-viltify:*" to figure out if any version is installable, or "composer require dalpizzol/laravel-viltify:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

**Comment by rodrigomgrassioto** [comment]
Tive o mesmo problema aqui. Inclui em package.json 
 "serve": "NODE_OPTIONS=--openssl-legacy-provider vue-cli-service serve",
        "build": "NODE_OPTIONS=--openssl-legacy-provider vue-cli-service build"

mas não resolveu

**Comment by MtDalPizzol** [comment]
Hi folks. I still need to update Viltify to work with Laravel 9. As soon as I can I'll revisit it. Pull requests are welcome.

**Comment by MtDalPizzol** [comment]
Hi, folks. Just released v0.2.0 with support for Laravel 9, Vue CLI 5 and TailwindCSS 3. Can you try it out and confirm if it's working now?

**Comment by thomasdeater** [comment]
I'm getting a different error now:

`🔋  16:15 in viltify/
› php artisan viltify:install

Info from https://repo.packagist.org: #StandWithUkraine
Using version ^0.5.4 for inertiajs/inertia-laravel
./composer.json has been updated
Running composer update inertiajs/inertia-laravel
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking inertiajs/inertia-laravel (v0.5.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading inertiajs/inertia-laravel (v0.5.4)
  - Installing inertiajs/inertia-laravel (v0.5.4): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: dalpizzol/laravel-viltify
Discovered Package: inertiajs/inertia-laravel
Discovered Package: laravel/sail
Discovered Package: laravel/sanctum
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: spatie/laravel-ignition
Package manifest generated successfully.
79 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan vendor:publish --tag=laravel-assets --ansi --force
No publishable resources for tag [laravel-assets].
Publishing complete.
Inertia adapter registered successfully.
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^1.4 for tightenco/ziggy
./composer.json has been updated
Running composer update tightenco/ziggy
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking tightenco/ziggy (v1.4.3)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading tightenco/ziggy (v1.4.3)
  - Installing tightenco/ziggy (v1.4.3): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: dalpizzol/laravel-viltify
Discovered Package: inertiajs/inertia-laravel
Discovered Package: laravel/sail
Discovered Package: laravel/sanctum
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: spatie/laravel-ignition
Discovered Package: tightenco/ziggy
Package manifest generated successfully.
79 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan vendor:publish --tag=laravel-assets --ansi --force
No publishable resources for tag [laravel-assets].
Publishing complete.
Ziggy installed successfully.
Routes copied successfully.
Configured views paths successfuly.
sh: line 0: exec: vue: not found
Couldn't create Vue CLI project.
Language resources copied successfuly.
Vue CLI project renamed successfuly.

   Symfony\Component\Process\Exception\RuntimeException

  The provided cwd "/Users/tdeater/Code/viltify/resources" does not exist.

  at vendor/symfony/process/Process.php:344
    340▕             }
    341▕         }
    342▕
    343▕         if (!is_dir($this->cwd)) {
  ➜ 344▕             throw new RuntimeException(sprintf('The provided cwd "%s" does not exist.', $this->cwd));
    345▕         }
    346▕
    347▕         $this->process = @proc_open($commandline, $descriptors, $this->processPipes->pipes, $this->cwd, $envPairs, $this->options);
    348▕

      +17 vendor frames
  18  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))`

**Comment by MtDalPizzol** [comment]
@thomasdeater Are you running Windows? VILTify only runs on Windows via WSL as stated in the README.

**Comment by thomasdeater** [comment]
Sorry, I was just about to edit my last comment. I had neglected to install vue-cli  on this Macbook prior to running viltify:install.

Seems to be up and running now!

<img width="751" alt="image" src="https://user-images.githubusercontent.com/514954/157315545-16563ee4-2660-4893-b8f4-04802383766d.png">
