### ISSUE TITLE
vue-github-button vue 3 issue

### ISSUE THREAD

**Issue by aneesdev** [MtDalPizzol/laravel-viltify#6]
Hi @MtDalPizzol,

First of all thanks for the great starter kit. appreciate all the hard work you did.

I installed this starter kit as mentioned in the readme file. when I did `npm run serve` I got `vue-github-button` error. after investigation it was that `vue-github-button` for vue 2 is `npm install vue-github-button@1` and not `npm install vue-github-button` cause the package is using vue 2.

**Comment by aneesdev** [comment]
https://github.com/MtDalPizzol/laravel-viltify/blob/4645ab50245f475112e4f0e3fcda32bbc9ea652c/src/Console/InstallCommand.php#L156

here it should be `vue-github-button@1`

**Comment by MtDalPizzol** [comment]
Hi, @aneesdev !

Thanks for the heads up and also for taking the time to figure out the solution.

Should be fixed now.
